name = "great-yarmouth-plumbers-co-uk"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "greatyarmouthplumbers.co.uk/*", zone_name = "greatyarmouthplumbers.co.uk" },
  { pattern = "www.greatyarmouthplumbers.co.uk/*", zone_name = "greatyarmouthplumbers.co.uk" }
]

[assets]
directory = "./dist"
